version: '3.8'

services:
  mariadb:
    build: ./srcs/mariadb
    container_name: mariadb
    env_file: ./srcs/.env
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - inception
    restart: always

  wordpress:
    build: ./srcs/wordpress
    container_name: wordpress
    env_file: ./srcs/.env
    depends_on:
      - mariadb
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - inception
    restart: always

  nginx:
    build: ./srcs/nginx
    container_name: nginx
    depends_on:
      - wordpress
    ports:
      - "443:443"
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - inception
    restart: always

volumes:
  mariadb_data:
    driver: local
    driver_opts:
      type: none
      device: /home/mery/data/mariadb
      o: bind

  wordpress_data:
    driver: local
    driver_opts:
      type: none
      device: /home/mery/data/wordpress
      o: bind

networks:
  inception:
    driver: bridge
